server:
  port: 9602
spring:
  security:
    user:
      name: admin
      password: 123456
  cloud:
    nacos:
      discovery:
        metadata:
          user.name: admin
          user.password: 123456
        enabled: true
        naming-load-cache-at-start: true
        password: nacos
        username: nacos
        heart-beat-interval: 6000
        namespace: public
        group: group
        service: ${spring.application.name}
        ip-delete-timeout: 600000
        instance-enabled: true
        server-addr: localhost:8848
  #配置sleuth
  sleuth:
    annotation:
      enabled: false
    enabled: false
    circuitbreaker:
      enabled: true
    async:
      configurer:
        enabled: true
    http:
      enabled: true
    sampler:
      rate: 12
      probability: 1.0
    web:
      enabled: true
    feign:
      enabled: true
  zipkin:
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
    compression:
      enabled: true
    enabled: true
    sender:
      type: web
    discovery-client-enabled: false

#全部放开
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
#dubbo配置
# Base packages to scan Dubbo Components (e.g @Service , @Reference)
dubbo:
  application:
    name: dubbo-sleuth-consume
    id: dubbo-sleuth-consume
    architecture: dubbo-spring-boot
  #dubbo协议
  protocol:
    name: dubbo
    port: -1
  monitor:
    protocol: dubbo
    address: N/A
  #dubbo注册
  registry:
    id: dubbo-sleuth-consume-service
    address: localhost:8848
    protocol: nacos
    port: 8848
    timeout: 2000
    group: group
  scan:
    base-packages: com.turboic.cloud.api
