server:
  port: 8001 #服务注册中心端口号
eureka:
  instance:
    hostname: 127.0.0.1 #服务注册中心IP地址
    metadata-map:
      user:
        name: admin
        password: 123456
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
# 开启基于http basic的安全认证
spring:
  security:
    user:
      name: admin
      password: 123456
