


server:
  port: 3000
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   vm
spring:
  security:
    user:
      name: admin
      password: 123456
      roles: admin,user
